# Generated by Django 4.2.10 on 2024-02-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('facility_name', models.CharField(max_length=100)),
                ('facilty_id', models.CharField(max_length=100)),
                ('month', models.DateField()),
                ('metformin', models.BooleanField(default=True)),
                ('sulfonylurea', models.BooleanField(default=True)),
                ('insulin', models.BooleanField(default=True)),
                ('statin', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'facilities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('birthdate', models.DateField()),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='datamanager.facilities')),
            ],
            options={
                'db_table': 'patients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HtnVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('ckd_diagnosis', models.BooleanField(default=True)),
                ('cvd_diagnosis', models.BooleanField(default=True)),
                ('cvd_high_risk', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=True)),
                ('sbp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dbp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('visit_type', models.CharField(choices=[('initial', 'Initial Visit'), ('followup', 'Follow Up Visit')], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='datamanager.patients')),
            ],
            options={
                'db_table': 'htn_visits',
                'managed': True,
            },
        ),
    ]
