# Generated by Django 4.2.10 on 2024-02-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilities',
            old_name='facilty_id',
            new_name='facility_id',
        ),
    ]
