# Generated by Django 4.2.10 on 2024-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0002_rename_facilty_id_facilities_facility_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
