# Generated by Django 4.2.10 on 2024-02-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0003_alter_patients_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htnvisits',
            name='dbp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='htnvisits',
            name='sbp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
