# Generated by Django 4.2.10 on 2024-02-25 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0004_alter_htnvisits_dbp_alter_htnvisits_sbp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTNIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(choices=[('BP_CONTROL', 'Blood pressure control among people with hypertension'), ('DIABETES_MED_AVAILABILITY', 'Availability of diabetes core medicines')], max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.facilities')),
            ],
            options={
                'db_table': 'htn_indicators',
                'managed': True,
            },
        ),
    ]
