# Generated by Django 4.2.10 on 2024-02-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0006_rename_value_htnindicators_cvd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='htnindicators',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='htn_indicators', to='datamanager.patients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='htnindicators',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='htn_indicators', to='datamanager.facilities'),
        ),
    ]
