# Generated by Django 4.2.10 on 2024-02-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0007_htnindicators_patient_alter_htnindicators_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htnindicators',
            name='cvd',
        ),
        migrations.RemoveField(
            model_name='htnindicators',
            name='measurements',
        ),
        migrations.AddField(
            model_name='htnindicators',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='htnindicators',
            name='high_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='htnindicators',
            name='low_risk',
            field=models.BooleanField(default=False),
        ),
    ]
