# Generated by Django 4.2.10 on 2024-02-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0008_remove_htnindicators_cvd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htnindicators',
            name='low_risk',
        ),
    ]
