# Generated by Django 4.2.10 on 2024-02-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0011_rename_created_at_htnindicators_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htnindicators',
            name='visit_date',
            field=models.DateField(),
        ),
    ]
