# Generated by Django 4.2.10 on 2024-02-29 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0012_alter_htnindicators_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htnindicators',
            name='visit_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 11, 49, 1, 906775)),
        ),
    ]
